### ISSUE TITLE
Error: Cannot find module esprima

### ISSUE THREAD

**Issue by wkruse** [contentful/contentful-cli#2348]
## Expected Behavior

Running standalone `contentful space export ...` should work.

Following standalone Linux versions **work**

- v2.2.24
- v2.6.46
- v2.7.0
- v2.8.9

## Actual Behavior

Running standalone `contentful space export ...` results in following exception:

```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module 'esprima'
Require stack:
- aesprim
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/snapshot/project/node_modules/jsonpath/lib/aesprim.js:4:20)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.<anonymous> (/snapshot/project/node_modules/jsonpath/lib/aesprim.js:15:11)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/project/node_modules/jsonpath/lib/handlers.js:1:77)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'aesprim' ],
  pkg: true
}

Node.js v18.5.0
```

Following versions are broken

- v2.8.10
- v2.8.27
- v3.0.5

## Possible Solution

Downgrading to a version that works, like **v2.8.9**.

## Environment

-   **Operating System**: `Linux d7b3a835dbcd 6.4.16-linuxkit #1 SMP PREEMPT Sat Sep 23 13:36:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jjolton-contentful** [comment]
release is building now, gonna reopen this until I can verify it is all fixed up :)

**Comment by jjolton-contentful** [comment]
Confirmed working on latest 3.1.3. Thanks for bringing this up @wkruse, let us know if you are still having any issues.

**Comment by wkruse** [comment]
@jjolton-contentful I **cannot** confirm it working.

Running standalone Linux version

```
contentful --version
3.1.3
```

when running following command

```
contentful space export --space-id xxx --environment-id yyy --max-allowed-limit 100 --skip-content true --content-file content-types-backup-yyy.json
```

I am still getting

```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module 'esprima'
Require stack:
- aesprim
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/snapshot/project/node_modules/jsonpath/lib/aesprim.js:4:20)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.<anonymous> (/snapshot/project/node_modules/jsonpath/lib/aesprim.js:15:11)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/project/node_modules/jsonpath/lib/handlers.js:1:77)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'aesprim' ],
  pkg: true
}

Node.js v18.5.0
```

**Comment by jjolton-contentful** [comment]
Copy that @wkruse, will investigate further with haste

**Comment by jjolton-contentful** [comment]
This upcoming release should do the trick

**Comment by wkruse** [comment]
Cannot reproduce the issue anymore with 3.1.4. Thank you!
